---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: namespace-and-secret
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Configuration Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # First, ensure the namespace exists
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-app-namespace
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: my-app
              labels:
                managed-by: rhacm
                app: my-application
  # Then create the secret in that namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-app-secret
      spec:
        remediationAction: enforce
        severity: medium
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: app-config
              namespace: my-app
              labels:
                managed-by: rhacm
            type: Opaque
            stringData:
              # Demo values - use external secret store in production
              database-host: "postgresql.example.com"
              database-port: "5432"
              database-name: "myapp_db"
              cache-endpoint: "redis://cache.example.com:6379"
              log-level: "info"

