---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: simple-secret-distribution
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication and Access Control
    policy.open-cluster-management.io/controls: PR.AC-1 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: simple-secret-config
      spec:
        remediationAction: enforce
        severity: medium
        namespaceSelector:
          include:
          - default
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: my-app-secret
              namespace: default
            type: Opaque
            stringData:
              # WARNING: This is for demo purposes only!
              # Do NOT commit real secrets to Git
              # Use External Secrets Operator or sealed secrets in production
              username: "demo-user"
              api-endpoint: "https://api.example.com"
              environment: "managed-cluster"

