---
# Policy to sync PostgreSQL database credentials from external store
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: postgresql-database-secret
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data Protection
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-postgresql-externalsecret
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: postgresql-credentials
              namespace: production-apps
              labels:
                managed-by: rhacm
                database-type: postgresql
            spec:
              refreshInterval: 1h
              secretStoreRef:
                name: vault-backend
                kind: SecretStore
              target:
                name: database-credentials
                creationPolicy: Owner
                deletionPolicy: Retain
                template:
                  engineVersion: v2
                  type: Opaque
                  metadata:
                    labels:
                      app: my-application
                      managed-by: rhacm
                  data:
                    # Individual database connection parameters
                    DB_USERNAME: "{{ .username }}"
                    DB_PASSWORD: "{{ .password }}"
                    DB_HOST: "{{ .host }}"
                    DB_PORT: "{{ .port }}"
                    DB_NAME: "{{ .database }}"
                    DB_SSLMODE: "{{ .sslmode }}"
                    
                    # PostgreSQL connection URL (standard format)
                    DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}?sslmode={{ .sslmode }}"
                    
                    # Alternative postgres:// format
                    POSTGRES_URL: "postgres://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}"
                    
                    # JDBC connection string
                    JDBC_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .database }}?sslmode={{ .sslmode }}"
              data:
              - secretKey: username
                remoteRef:
                  key: database/production
                  property: username
              - secretKey: password
                remoteRef:
                  key: database/production
                  property: password
              - secretKey: host
                remoteRef:
                  key: database/production
                  property: host
              - secretKey: port
                remoteRef:
                  key: database/production
                  property: port
              - secretKey: database
                remoteRef:
                  key: database/production
                  property: database
              - secretKey: sslmode
                remoteRef:
                  key: database/production
                  property: sslmode

