---
# Policy to configure AWS Secrets Manager SecretStore
# Uses IAM Roles for Service Accounts (IRSA) for authentication
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aws-secretstore-config
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication
    policy.open-cluster-management.io/controls: PR.AC-1 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Create namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-app-namespace
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: my-app
              labels:
                managed-by: rhacm
  
  # Create ServiceAccount with IAM role annotation (for IRSA)
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: eso-aws-serviceaccount
      spec:
        remediationAction: enforce
        severity: medium
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: external-secrets-aws
              namespace: my-app
              annotations:
                # For EKS
                eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/external-secrets-role"
                # For ROSA/ARO
                # rosa.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/external-secrets-role"
              labels:
                managed-by: rhacm
  
  # Configure ClusterSecretStore for AWS Secrets Manager
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: aws-cluster-secretstore
      spec:
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: ClusterSecretStore
            metadata:
              name: aws-secrets-manager
              labels:
                managed-by: rhacm
            spec:
              provider:
                aws:
                  service: SecretsManager
                  region: us-east-1
                  auth:
                    jwt:
                      serviceAccountRef:
                        name: external-secrets-aws
                        namespace: my-app
---
# Alternative: SecretStore with static credentials (NOT recommended for production)
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: aws-secretstore-static-creds
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: true  # Disabled by default - use IRSA instead
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: aws-static-credentials
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        # Create secret with AWS credentials
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: aws-credentials
              namespace: my-app
            type: Opaque
            stringData:
              access-key-id: "AKIAIOSFODNN7EXAMPLE"
              secret-access-key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        # Configure SecretStore
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: SecretStore
            metadata:
              name: aws-backend-static
              namespace: my-app
            spec:
              provider:
                aws:
                  service: SecretsManager
                  region: us-east-1
                  auth:
                    secretRef:
                      accessKeyIDSecretRef:
                        name: aws-credentials
                        key: access-key-id
                      secretAccessKeySecretRef:
                        name: aws-credentials
                        key: secret-access-key

