---
# Policy to configure Azure Key Vault SecretStore
# Uses Managed Identity for authentication
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: azure-keyvault-config
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication
    policy.open-cluster-management.io/controls: PR.AC-1 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Create namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-app-namespace
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: my-app
              labels:
                managed-by: rhacm
  
  # Configure SecretStore with Managed Identity
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: azure-keyvault-secretstore
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: SecretStore
            metadata:
              name: azure-keyvault
              namespace: my-app
              labels:
                managed-by: rhacm
            spec:
              provider:
                azurekv:
                  authType: ManagedIdentity
                  vaultUrl: "https://my-keyvault.vault.azure.net"
                  # Replace with your User-Assigned Managed Identity Client ID
                  identityId: "00000000-0000-0000-0000-000000000000"
---
# Alternative: Azure Service Principal authentication
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: azure-keyvault-sp-auth
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: true  # Disabled - prefer Managed Identity
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: azure-sp-credentials
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        # Create Service Principal credentials secret
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: azure-sp-credentials
              namespace: my-app
            type: Opaque
            stringData:
              client-id: "00000000-0000-0000-0000-000000000000"
              client-secret: "your-client-secret-here"
        # Configure SecretStore with Service Principal
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: SecretStore
            metadata:
              name: azure-keyvault-sp
              namespace: my-app
            spec:
              provider:
                azurekv:
                  authType: ServicePrincipal
                  vaultUrl: "https://my-keyvault.vault.azure.net"
                  tenantId: "00000000-0000-0000-0000-000000000000"
                  authSecretRef:
                    clientId:
                      name: azure-sp-credentials
                      key: client-id
                    clientSecret:
                      name: azure-sp-credentials
                      key: client-secret

