---
# Policy to create ExternalSecret for database credentials
# Syncs secrets from external store to Kubernetes
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: database-external-secret
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data Protection
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: sync-database-credentials
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: database-credentials
              namespace: my-app
              labels:
                managed-by: rhacm
                app: my-application
            spec:
              # Refresh interval - how often to sync from external store
              refreshInterval: 1h
              
              # Reference to SecretStore
              secretStoreRef:
                name: vault-backend  # Change to your SecretStore name
                kind: SecretStore
              
              # Target Kubernetes Secret
              target:
                name: database-credentials
                creationPolicy: Owner  # ESO owns and manages this secret
                deletionPolicy: Retain  # Keep secret if ExternalSecret deleted
                
                # Template the secret data
                template:
                  engineVersion: v2
                  type: Opaque
                  data:
                    # Create connection string from individual fields
                    DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:5432/{{ .database }}"
                    
                    # Individual fields also available
                    DB_USERNAME: "{{ .username }}"
                    DB_PASSWORD: "{{ .password }}"
                    DB_HOST: "{{ .host }}"
                    DB_PORT: "5432"
                    DB_NAME: "{{ .database }}"
              
              # Define which secrets to fetch
              data:
              - secretKey: username
                remoteRef:
                  key: database/production  # Path in Vault
                  property: username
              
              - secretKey: password
                remoteRef:
                  key: database/production
                  property: password
              
              - secretKey: host
                remoteRef:
                  key: database/production
                  property: host
              
              - secretKey: database
                remoteRef:
                  key: database/production
                  property: database
---
# Alternative: Fetch entire secret at once
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: database-external-secret-datafrom
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: sync-database-all-fields
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: database-all-fields
              namespace: my-app
            spec:
              refreshInterval: 15m
              secretStoreRef:
                name: vault-backend
                kind: SecretStore
              target:
                name: database-config
                creationPolicy: Owner
              # Extract all key-value pairs from the secret
              dataFrom:
              - extract:
                  key: database/production

