---
# RHACM 2.15+ Best Practice: Use Placement API with ManagedClusterSet

# ManagedClusterSet for all managed clusters
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: global
spec:
  clusterSelector:
    selectorType: LabelSelector
    labelSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - local-cluster
---
# Bind global ManagedClusterSet to namespace
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: rhacm-policies
spec:
  clusterSet: global
---
# ManagedClusterSet for production clusters
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: production
spec:
  clusterSelector:
    selectorType: LabelSelector
    labelSelector:
      matchLabels:
        environment: production
---
# Bind production ManagedClusterSet to namespace
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: production
  namespace: rhacm-policies
spec:
  clusterSet: production
---
# Placement for all managed clusters
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-managed-clusters
  namespace: rhacm-policies
spec:
  clusterSets:
  - global
  
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
---
# Placement for production clusters only
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: production-clusters
  namespace: rhacm-policies
spec:
  clusterSets:
  - production
  
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
---
# Bind ESO installation to all clusters
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-install-eso-all
  namespace: rhacm-policies
placementRef:
  name: all-managed-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: install-external-secrets-operator
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
# Bind Vault SecretStore config to production clusters
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-vault-secretstore-prod
  namespace: rhacm-policies
placementRef:
  name: production-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: vault-secretstore-config
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
# Bind database ExternalSecret to production clusters
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-database-secret-prod
  namespace: rhacm-policies
placementRef:
  name: production-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: database-external-secret
  kind: Policy
  apiGroup: policy.open-cluster-management.io
