---
# Policy to configure Vault SecretStore and ExternalSecret
# This example uses Vault token authentication
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vault-secretstore-config
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication
    policy.open-cluster-management.io/controls: PR.AC-1 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Create application namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-app-namespace
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: my-app
              labels:
                managed-by: rhacm
                external-secrets: enabled
  
  # Create Vault authentication token secret
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: vault-auth-token
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: vault-token
              namespace: my-app
              labels:
                managed-by: rhacm
            type: Opaque
            stringData:
              # REPLACE with actual Vault token or use Hub secret reference
              # In production, use: '{{hub fromSecret "vault-namespace" "vault-secret" "token" hub}}'
              token: "hvs.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  
  # Configure Vault SecretStore
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: vault-secretstore
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: external-secrets.io/v1beta1
            kind: SecretStore
            metadata:
              name: vault-backend
              namespace: my-app
              labels:
                managed-by: rhacm
            spec:
              provider:
                vault:
                  server: "https://vault.example.com:8200"
                  path: "secret"  # KV v2 mount path
                  version: "v2"   # KV version
                  auth:
                    tokenSecretRef:
                      name: vault-token
                      key: token
              # Optional: Configure retry and timeout
              retrySettings:
                maxRetries: 3
                retryInterval: "10s"

