#!/usr/bin/env bash
# render-clusters.sh — APPROACH A ONLY (DEPRECATED for this repo)
#
# This script implements Approach A: render per-cluster Application files
# using charts/cluster-apps and commit them to clusters/<name>/rendered/.
#
# THIS REPO NOW USES APPROACH B (hub-clusters + hub-bootstrap).
# In Approach B, cluster values files use a different schema (no groups: or
# cluster: blocks) and there are no per-cluster rendered/ directories.
# The hub-level rendered output lives in hub/rendered/hub-applications.yaml,
# generated by the GitHub Action in .github/workflows/render-hub-applications.yml.
#
# This script is kept as a reference for Approach A. To use it you would need
# cluster values files that include groups: and component-<name>.cluster: blocks.
# See the README Approach A section for the required schema.
#
# Usage (Approach A):
#   ./scripts/render-clusters.sh [cluster-name]
#
#   With no argument: renders all clusters.
#   With a cluster name: renders only that cluster.
#
# Requirements: helm >= 3.10, yq >= 4.x (mikefarah/yq)
#
# How it works:
#   1. For each cluster directory, read the groups: list from values.yaml
#      using yq.
#   2. Build --values flags in order: each group file first, then the
#      cluster file last (highest priority).
#   3. Call helm template with the assembled flags. The chart template
#      uses mustMergeOverwrite to merge all component-* keys in load order.
#   4. Write the rendered YAML to clusters/<name>/rendered/applications.yaml.
#
# The rendered output is committed to Git so that:
#   - Every change is visible as a diff before Argo CD applies it.
#   - CI can validate rendered Applications with kubeval or conftest.
#   - Reviewers see exactly what will be deployed, not a template.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATTERN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHART="${PATTERN_ROOT}/charts/cluster-apps"
CLUSTERS_DIR="${PATTERN_ROOT}/clusters"
GROUPS_DIR="${PATTERN_ROOT}/groups"

# ── Dependency checks ────────────────────────────────────────────────────────
if ! command -v helm &>/dev/null; then
  echo "ERROR: helm is not installed or not in PATH" >&2; exit 1
fi
if ! command -v yq &>/dev/null; then
  echo "ERROR: yq is not installed or not in PATH (install: https://github.com/mikefarah/yq)" >&2; exit 1
fi

# ── Cluster selection ────────────────────────────────────────────────────────
if [[ $# -gt 0 ]]; then
  TARGET_CLUSTERS=("$1")
else
  mapfile -t TARGET_CLUSTERS < <(find "${CLUSTERS_DIR}" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)
fi

# ── Render loop ──────────────────────────────────────────────────────────────
for cluster in "${TARGET_CLUSTERS[@]}"; do
  cluster_dir="${CLUSTERS_DIR}/${cluster}"
  cluster_values="${cluster_dir}/values.yaml"
  rendered_dir="${cluster_dir}/rendered"
  rendered_out="${rendered_dir}/applications.yaml"

  if [[ ! -f "${cluster_values}" ]]; then
    echo "SKIP: ${cluster} — no values.yaml found at ${cluster_values}"
    continue
  fi

  echo "→ Rendering cluster: ${cluster}"

  # ── Step 1: Read the groups list from the cluster values file ─────────────
  # yq returns a newline-separated list of group names.
  mapfile -t groups < <(yq '.groups[]' "${cluster_values}" 2>/dev/null || true)

  # ── Step 2: Build ordered --values flags ──────────────────────────────────
  # Group files are loaded in declaration order (lower index = lower priority).
  # Cluster file is always last (highest priority).
  values_flags=()
  for group in "${groups[@]}"; do
    group_file="${GROUPS_DIR}/${group}/values.yaml"
    if [[ -f "${group_file}" ]]; then
      values_flags+=("--values" "${group_file}")
    else
      echo "  WARN: group '${group}' declared in ${cluster} but no values file at ${group_file}" >&2
    fi
  done
  values_flags+=("--values" "${cluster_values}")

  # ── Step 3: Render ────────────────────────────────────────────────────────
  mkdir -p "${rendered_dir}"

  # Emit a header comment so reviewers know this file is generated.
  {
    echo "# Generated by scripts/render-clusters.sh — do not edit by hand."
    echo "# Cluster: ${cluster}"
    echo "# Groups:  ${groups[*]:-none}"
    echo "# Rendered: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "# Re-render: ./scripts/render-clusters.sh ${cluster}"
    echo "#"
    echo "# mustMergeOverwrite resolution order (lowest → highest priority):"
    for group in "${groups[@]}"; do
      echo "#   component-${group}  (groups/${group}/values.yaml)"
    done
    echo "#   component-${cluster}  (clusters/${cluster}/values.yaml)"
    echo ""

    helm template "${cluster}-apps" "${CHART}" \
      "${values_flags[@]}"
  } > "${rendered_out}"

  echo "  ✓ Written: ${rendered_out}"
done

echo ""
echo "Done. Review the rendered files before committing:"
for cluster in "${TARGET_CLUSTERS[@]}"; do
  rendered="${CLUSTERS_DIR}/${cluster}/rendered/applications.yaml"
  [[ -f "${rendered}" ]] && echo "  ${rendered}"
done
