---
# Complete examples: Using copySecretData to reference secrets from different namespaces
# RHACM 2.8+ feature

# copySecretData allows you to copy entire secrets or specific keys from Hub cluster
# secrets in different namespaces to managed clusters

# Example 1: Copy Entire Secret from Different Namespace
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-secret-from-vault-ns
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-complete-secret
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        # copySecretData copies secrets from Hub to managed cluster
        copySecretData:
        - sourceNamespace: vault-secrets  # Different namespace on Hub
          sourceName: database-credentials
          targetNamespace: production-apps
          targetName: database-credentials

---
# Example 2: Copy Multiple Secrets from Different Namespaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-multiple-secrets
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-multiple
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        copySecretData:
        # Copy database credentials from vault-secrets namespace
        - sourceNamespace: vault-secrets
          sourceName: database-credentials
          targetNamespace: production-apps
          targetName: db-creds
        # Copy API keys from api-secrets namespace
        - sourceNamespace: api-secrets
          sourceName: external-api-keys
          targetNamespace: production-apps
          targetName: api-keys
        # Copy TLS certificates from certificate-manager namespace
        - sourceNamespace: certificate-manager
          sourceName: wildcard-tls-cert
          targetNamespace: production-apps
          targetName: tls-cert

---
# Example 3: Copy Secret to Multiple Target Namespaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-secret-to-multiple-namespaces
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-registry-creds-multiple
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
          - staging-apps
          - dev-apps
        copySecretData:
        # Same source secret copied to multiple target namespaces
        - sourceNamespace: registry-secrets
          sourceName: quay-pull-secret
          # targetNamespace will be each namespace from namespaceSelector
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: registry-credentials

---
# Example 4: Copy Registry Secret (dockerconfigjson type)
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-registry-secret
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-registry-creds
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - "*"
          exclude:
          - kube-*
          - openshift-*
          - open-cluster-*
          - default
        copySecretData:
        # Copy registry credentials from central registry namespace
        - sourceNamespace: registry-credentials
          sourceName: production-registry
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: registry-pull-secret

---
# Example 5: Copy TLS Certificates from cert-manager Namespace
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-tls-certificates
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-tls-cert
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        copySecretData:
        # Copy TLS certificate from cert-manager namespace
        - sourceNamespace: cert-manager
          sourceName: wildcard-example-com
          targetNamespace: production-apps
          targetName: app-tls-cert

---
# Example 6: Combine copySecretData with fromSecret
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: combine-copy-and-fromsecret
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: hybrid-secret-management
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        # First, copy complete registry secret
        copySecretData:
        - sourceNamespace: registry-secrets
          sourceName: quay-credentials
          targetNamespace: production-apps
          targetName: registry-creds
        # Then, create additional secret with fromSecret for individual keys
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: database-config
              namespace: production-apps
            type: Opaque
            stringData:
              # Use fromSecret for individual key extraction
              db-username: '{{hub fromSecret "vault-secrets" "database-credentials" "username" hub}}'
              db-password: '{{hub fromSecret "vault-secrets" "database-credentials" "password" hub}}'
              db-host: '{{hub fromSecret "vault-secrets" "database-credentials" "host" hub}}'

---
# Example 7: Copy Secrets from Team-Specific Namespaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-team-secrets
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-team-alpha-secrets
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          matchLabels:
            team: alpha
        copySecretData:
        # Copy from team-alpha specific namespace on Hub
        - sourceNamespace: team-alpha-secrets
          sourceName: team-credentials
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: team-credentials

---
# Example 8: Copy Environment-Specific Secrets
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-env-specific-secrets
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Production secret
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-prod-secrets
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          matchLabels:
            environment: production
        copySecretData:
        # Copy from production-secrets namespace on Hub
        - sourceNamespace: production-secrets
          sourceName: app-credentials
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: app-credentials
  
  # Staging secret
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-staging-secrets
      spec:
        remediationAction: enforce
        severity: medium
        namespaceSelector:
          matchLabels:
            environment: staging
        copySecretData:
        # Copy from staging-secrets namespace on Hub
        - sourceNamespace: staging-secrets
          sourceName: app-credentials
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: app-credentials

---
# Example 9: Copy CA Bundle from Security Namespace
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: copy-ca-bundle
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: copy-corporate-ca
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - "*"
          exclude:
          - kube-*
          - openshift-*
        copySecretData:
        # Copy CA certificates from security namespace
        - sourceNamespace: security-certificates
          sourceName: corporate-ca-bundle
          targetNamespace: "{{ (lookup \"v1\" \"Namespace\" \"\" \"\").metadata.name }}"
          targetName: ca-certificates

---
# Example 10: PlacementBinding for copySecretData Policy
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: production
spec:
  clusterSelector:
    selectorType: LabelSelector
    labelSelector:
      matchLabels:
        environment: production
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: production
  namespace: rhacm-policies
spec:
  clusterSet: production
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: production-clusters
  namespace: rhacm-policies
spec:
  clusterSets:
  - production
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
---
# Bind policy to placement
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-copy-secrets
  namespace: rhacm-policies
placementRef:
  name: production-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: copy-secret-from-vault-ns
  kind: Policy
  apiGroup: policy.open-cluster-management.io

