---
# Example: Load secrets from Hub cluster and distribute to managed clusters
# Requirements: RHACM 2.8+ for fromSecret template function
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: secrets-from-hub
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data Protection
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: distribute-secrets-from-hub
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: application-secrets
              namespace: production-apps
              labels:
                managed-by: rhacm
                source: hub-cluster
            type: Opaque
            stringData:
              # Load individual keys from Hub secrets
              # Syntax: '{{hub fromSecret "namespace" "secret-name" "key" hub}}'
              
              # Database credentials from Hub
              DB_USERNAME: '{{hub fromSecret "rhacm-secrets" "prod-database" "username" hub}}'
              DB_PASSWORD: '{{hub fromSecret "rhacm-secrets" "prod-database" "password" hub}}'
              DB_HOST: '{{hub fromSecret "rhacm-secrets" "prod-database" "host" hub}}'
              DB_PORT: '{{hub fromSecret "rhacm-secrets" "prod-database" "port" hub}}'
              DB_NAME: '{{hub fromSecret "rhacm-secrets" "prod-database" "database" hub}}'
              
              # API keys from different Hub secret
              API_KEY: '{{hub fromSecret "rhacm-secrets" "api-credentials" "api-key" hub}}'
              API_SECRET: '{{hub fromSecret "rhacm-secrets" "api-credentials" "api-secret" hub}}'
              
              # Compose connection string using Hub secrets
              DATABASE_URL: 'postgresql://{{hub fromSecret "rhacm-secrets" "prod-database" "username" hub}}:{{hub fromSecret "rhacm-secrets" "prod-database" "password" hub}}@{{hub fromSecret "rhacm-secrets" "prod-database" "host" hub}}:5432/{{hub fromSecret "rhacm-secrets" "prod-database" "database" hub}}'
              
              # Static values can be mixed with Hub secrets
              ENVIRONMENT: "production"
              LOG_LEVEL: "info"

