---
# RHACM 2.15+ Best Practice: Use Placement API with ManagedClusterSet
# This file demonstrates the modern Placement API replacing deprecated PlacementRule

# ManagedClusterSet for production clusters
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: production
spec:
  clusterSelector:
    selectorType: LabelSelector
    labelSelector:
      matchLabels:
        environment: production
---
# Bind production ManagedClusterSet to namespace
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: production
  namespace: rhacm-policies
spec:
  clusterSet: production
---
# ManagedClusterSet for all managed clusters
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: global
spec:
  clusterSelector:
    selectorType: LabelSelector
    labelSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - local-cluster
---
# Bind global ManagedClusterSet to namespace
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: rhacm-policies
spec:
  clusterSet: global
---
# Placement for production clusters
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: production-clusters
  namespace: rhacm-policies
spec:
  clusterSets:
  - production
  
  # Tolerate temporary unavailability
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
---
# Placement for all managed clusters
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-managed-clusters
  namespace: rhacm-policies
spec:
  clusterSets:
  - global
  
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
---
# PlacementBinding: Bind Hub secret reference policy to production clusters
# Note the changes from PlacementRule:
#   - kind: Placement (not PlacementRule)
#   - apiGroup: cluster.open-cluster-management.io (not apps.open-cluster-management.io)
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-hub-secrets-prod
  namespace: rhacm-policies
placementRef:
  name: production-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: secrets-from-hub
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
# Bind registry credentials to all clusters
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-registry-from-hub-all
  namespace: rhacm-policies
placementRef:
  name: all-managed-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: registry-credentials-from-hub
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
# Bind TLS certificates to production clusters
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-tls-from-hub-prod
  namespace: rhacm-policies
placementRef:
  name: production-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: tls-certificates-from-hub
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: ca-bundle-from-hub
  kind: Policy
  apiGroup: policy.open-cluster-management.io
