---
# Policy to distribute container registry credentials
# This example shows Docker Hub credentials
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: docker-hub-credentials
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication
    policy.open-cluster-management.io/controls: PR.AC-7 Wireless Access
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Create application namespace if it doesn't exist
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: ensure-namespace-exists
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: production-apps
              labels:
                managed-by: rhacm
  
  # Create Docker Hub pull secret
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: docker-hub-pull-secret
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - production-apps
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: docker-hub-credentials
              namespace: production-apps
              labels:
                managed-by: rhacm
            type: kubernetes.io/dockerconfigjson
            stringData:
              # REPLACE with your actual credentials
              # Generate with: kubectl create secret docker-registry <name> \
              #   --docker-server=docker.io \
              #   --docker-username=<user> \
              #   --docker-password=<pass> \
              #   --dry-run=client -o yaml
              .dockerconfigjson: |
                {
                  "auths": {
                    "docker.io": {
                      "username": "your-username",
                      "password": "your-token",
                      "auth": "eW91ci11c2VybmFtZTp5b3VyLXRva2Vu"
                    }
                  }
                }

