---
# Policy to create ServiceAccount with imagePullSecrets
# Any Pod using this ServiceAccount automatically gets registry access
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: serviceaccount-with-registry-access
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management Authentication
    policy.open-cluster-management.io/controls: PR.AC-1 Access Control
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  # Create namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: ensure-app-namespace
      spec:
        remediationAction: enforce
        severity: low
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: my-app
              labels:
                managed-by: rhacm
  
  # Create registry pull secret
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-registry-secret
      spec:
        remediationAction: enforce
        severity: high
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: quay-credentials
              namespace: my-app
              labels:
                managed-by: rhacm
            type: kubernetes.io/dockerconfigjson
            stringData:
              .dockerconfigjson: |
                {
                  "auths": {
                    "quay.io": {
                      "username": "your-username",
                      "password": "your-token",
                      "auth": "eW91ci11c2VybmFtZTp5b3VyLXRva2Vu"
                    }
                  }
                }
  
  # Create ServiceAccount with imagePullSecrets
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: create-serviceaccount-with-pullsecret
      spec:
        remediationAction: enforce
        severity: medium
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: app-deployer
              namespace: my-app
              labels:
                managed-by: rhacm
            imagePullSecrets:
            - name: quay-credentials
  
  # Optional: Create a RoleBinding to allow pods to use this ServiceAccount
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: allow-serviceaccount-usage
      spec:
        remediationAction: enforce
        severity: low
        namespaceSelector:
          include:
          - my-app
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: use-app-deployer-sa
              namespace: my-app
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: edit
            subjects:
            - kind: ServiceAccount
              name: app-deployer
              namespace: my-app

