---
- name: Complete IP Subnet Validation with Detailed Reporting
  hosts: localhost
  gather_facts: false
  
  vars:
    # Define your allowed subnets as a flat list
    allowed_subnets:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.1.0/24"
      - "203.0.113.0/24"
    
    # Define IP addresses to validate as a flat list
    ip_addresses_to_check:
      - "10.50.100.25"
      - "172.16.5.10"
      - "192.168.1.50"
      - "203.0.113.15"
      - "8.8.8.8"
      - "192.168.2.100"

  tasks:
    - name: Validate IP addresses against subnets
      block:
        - name: Check each IP against all subnets
          ansible.builtin.set_fact:
            ip_subnet_matches: "{{ ip_subnet_matches | default({}) | combine({item.0: (ip_subnet_matches | default({}))[item.0] | default({}) | combine({item.1: item.0 | ansible.utils.ipaddr(item.1)})}) }}"
          loop: "{{ ip_addresses_to_check | product(allowed_subnets) | list }}"
          loop_control:
            label: "{{ item.0 }} vs {{ item.1 }}"

        - name: Build detailed validation results
          ansible.builtin.set_fact:
            validation_details: >-
              {{
                validation_details | default([]) + [{
                  'ip': item,
                  'is_valid': ip_subnet_matches[item].values() | select() | list | length > 0,
                  'matching_subnets': valid_subnet_list
                }]
              }}
          vars:
            valid_subnet_list: "{{ ip_subnet_matches[item] | dict2items | selectattr('value', 'ne', '') | selectattr('value') | map(attribute='key') | list }}"
          loop: "{{ ip_addresses_to_check }}"
          loop_control:
            label: "{{ item }}"

        - name: Separate valid and invalid IPs
          ansible.builtin.set_fact:
            valid_ips: "{{ validation_details | selectattr('is_valid', 'equalto', true) | map(attribute='ip') | list }}"
            invalid_ips: "{{ validation_details | selectattr('is_valid', 'equalto', false) | map(attribute='ip') | list }}"

        - name: Display summary
          ansible.builtin.debug:
            msg:
              - "======================================"
              - "IP SUBNET VALIDATION SUMMARY"
              - "======================================"
              - "Total IPs checked: {{ validation_details | length }}"
              - "Valid IPs: {{ valid_ips | length }}"
              - "Invalid IPs: {{ invalid_ips | length }}"
              - ""

        - name: Display detailed results
          ansible.builtin.debug:
            msg:
              - "IP: {{ item.ip }}"
              - "Status: {{ 'VALID ✓' if item.is_valid else 'INVALID ✗' }}"
              - "Matching Subnets: {{ item.matching_subnets | join(', ') if item.matching_subnets else 'None' }}"
              - "---"
          loop: "{{ validation_details }}"
          loop_control:
            label: "{{ item.ip }}"

        - name: Fail if any invalid IPs found
          ansible.builtin.fail:
            msg: |
              Validation failed! The following IPs are not covered by allowed subnets:
              {% for ip in invalid_ips %}
              - {{ ip }}
              {% endfor %}
          when: invalid_ips | length > 0

      rescue:
        - name: Handle validation failure
          ansible.builtin.debug:
            msg: "Validation completed with errors. Check the results above."
