#!/usr/bin/env bash
# aggregate-cluster-config.sh
#
# Aggregates all clusters/<name>/cluster.yaml files into a single values.yaml
# for the cluster-label-sync Helm chart. This is the bridge between the
# per-cluster Git config and the centralized label enforcement policy chart.
#
# Usage:
#   bash aggregate-cluster-config.sh <framework-path>
#
# The output is written to both:
#   - <framework-path>/hub/rhacm/cluster-labels/values.yaml (in-place update)
#   - /tmp/aggregated-cluster-labels.yaml (for CI diff comparison)
#
# Run this script:
#   - Locally before committing cluster changes
#   - In CI to validate that values.yaml is up to date
#   - As a pre-commit hook to auto-update
#
# Requires: yq (https://github.com/mikefarah/yq)

set -euo pipefail

FRAMEWORK_PATH="${1:?Usage: $0 <framework-path>}"
OUTPUT_FILE="$FRAMEWORK_PATH/hub/rhacm/cluster-labels/values.yaml"
TMP_OUTPUT="/tmp/aggregated-cluster-labels.yaml"

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq is required. Install from https://github.com/mikefarah/yq"
  exit 1
fi

cat > "$TMP_OUTPUT" <<'HEADER'
# cluster-label-sync values
#
# AUTO-GENERATED by pipelines/github-actions/aggregate-cluster-config.sh
# DO NOT EDIT MANUALLY — edit clusters/<name>/cluster.yaml instead and re-run.
#
# Regenerate with:
#   bash pipelines/github-actions/aggregate-cluster-config.sh argo-examples/framework

policyNamespace: open-cluster-management-global-set
remediationAction: enforce

clusters:
HEADER

cluster_count=0

for cluster_dir in "$FRAMEWORK_PATH"/clusters/*/; do
  cluster_name=$(basename "$cluster_dir")

  # Skip template and non-directories
  [ "$cluster_name" = "_template" ] && continue
  [ ! -d "$cluster_dir" ] && continue

  cluster_yaml="$cluster_dir/cluster.yaml"
  [ ! -f "$cluster_yaml" ] && continue

  # Extract the managedClusterLabels from cluster.yaml
  labels=$(yq '.cluster.managedClusterLabels' "$cluster_yaml")
  if [ "$labels" = "null" ] || [ -z "$labels" ]; then
    echo "WARN: $cluster_name has no managedClusterLabels, skipping"
    continue
  fi

  # Append cluster entry
  cat >> "$TMP_OUTPUT" <<EOF
  - name: $cluster_name
    managedClusterLabels:
$(echo "$labels" | sed 's/^/      /')

EOF

  cluster_count=$((cluster_count + 1))
done

echo "Aggregated $cluster_count clusters into $TMP_OUTPUT"

# Copy to the chart values file
cp "$TMP_OUTPUT" "$OUTPUT_FILE"
echo "Updated $OUTPUT_FILE"
